AWSTemplateFormatVersion: 2010-09-09
Description: >- 
  Create a single EC2 instance with its resources and dependencies
Parameters: 
  KeyName:
    Description: KeyPair for enabling ssh purposes
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: Must be a valid EC2 Instance Type
  Mappings:
    AWSInstanceType2Arch:
      t2.nano:
        Arch: HVM64
      t2.micro:
        Arch: HVM64
      t2.small:
        Arch: HVM64
      t2.medium:
        Arch: HVM64
      t2.large:
        Arch: HVM64
Resources:
  ServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: >-
        Enable HTTP/S access via port 80,443 and SSH port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  Server:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-01419b804382064e4'
      InstanceType: !Ref InstanceType
      SecurityGroups: !Ref ServerSecurityGroup
      KeyName: !Ref KeyName
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          wordpress_install:
            - install_cfn
            - install_wordpress
  IPAddress:
    Type: 'AWS::EC2::EIP'
  IpAssoc:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      InstanceId: !Ref Server
      EIP: !Ref IPAddress 
Outputs:
  ServerName:
    Value: !Ref Server
    Description: Server Name
  WebsiteIPAddr:
    Value: !Ref IPAddress
    Description: Server IP Address